package com.example.demo.entities;
// Generated Dec 3, 2019 5:50:24 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name = "answer", catalog = "testingdb", uniqueConstraints = @UniqueConstraint(columnNames = { "EXAM_QUESTION_ID",
		"QUESTION_SUB_ID" }))
public class Answer implements java.io.Serializable {

	private Integer id;
	private ExamQuestion examQuestion;
	private QuestionSub questionSub;

	public Answer() {
	}

	public Answer(ExamQuestion examQuestion, QuestionSub questionSub) {
		this.examQuestion = examQuestion;
		this.questionSub = questionSub;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXAM_QUESTION_ID")
	public ExamQuestion getExamQuestion() {
		return this.examQuestion;
	}

	public void setExamQuestion(ExamQuestion examQuestion) {
		this.examQuestion = examQuestion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_SUB_ID")
	public QuestionSub getQuestionSub() {
		return this.questionSub;
	}

	public void setQuestionSub(QuestionSub questionSub) {
		this.questionSub = questionSub;
	}

}
