package com.example.demo.entities;
// Generated Dec 3, 2019 5:50:24 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "feedback", catalog = "testingdb")
public class Feedback implements java.io.Serializable {

	private Integer id;
	private Account accountByToId;
	private Account accountByFromId;
	private String subject;
	private String content;
	private Date createTime;
	private Set<ResponseFeedback> responseFeedbacks = new HashSet<ResponseFeedback>(0);

	public Feedback() {
	}

	public Feedback(Account accountByToId, Account accountByFromId, String subject, String content, Date createTime,
			Set<ResponseFeedback> responseFeedbacks) {
		this.accountByToId = accountByToId;
		this.accountByFromId = accountByFromId;
		this.subject = subject;
		this.content = content;
		this.createTime = createTime;
		this.responseFeedbacks = responseFeedbacks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TO_ID")
	public Account getAccountByToId() {
		return this.accountByToId;
	}

	public void setAccountByToId(Account accountByToId) {
		this.accountByToId = accountByToId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FROM_ID")
	public Account getAccountByFromId() {
		return this.accountByFromId;
	}

	public void setAccountByFromId(Account accountByFromId) {
		this.accountByFromId = accountByFromId;
	}

	@Column(name = "SUBJECT", length = 250)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "CONTENT", length = 250)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedback")
	public Set<ResponseFeedback> getResponseFeedbacks() {
		return this.responseFeedbacks;
	}

	public void setResponseFeedbacks(Set<ResponseFeedback> responseFeedbacks) {
		this.responseFeedbacks = responseFeedbacks;
	}

}
