package com.example.demo.entities;
// Generated Dec 3, 2019 5:50:24 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvoicePurchaseGems generated by hbm2java
 */
@Entity
@Table(name = "invoice_purchase_gems", catalog = "testingdb")
public class InvoicePurchaseGems implements java.io.Serializable {

	private Integer id;
	private Account accountByAccountId;
	private Account accountByAccountAcceptId;
	private Integer gems;
	private Date createTime;

	public InvoicePurchaseGems() {
	}

	public InvoicePurchaseGems(Account accountByAccountId, Account accountByAccountAcceptId, Integer gems,
			Date createTime) {
		this.accountByAccountId = accountByAccountId;
		this.accountByAccountAcceptId = accountByAccountAcceptId;
		this.gems = gems;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_ID")
	public Account getAccountByAccountId() {
		return this.accountByAccountId;
	}

	public void setAccountByAccountId(Account accountByAccountId) {
		this.accountByAccountId = accountByAccountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_ACCEPT_ID")
	public Account getAccountByAccountAcceptId() {
		return this.accountByAccountAcceptId;
	}

	public void setAccountByAccountAcceptId(Account accountByAccountAcceptId) {
		this.accountByAccountAcceptId = accountByAccountAcceptId;
	}

	@Column(name = "GEMS")
	public Integer getGems() {
		return this.gems;
	}

	public void setGems(Integer gems) {
		this.gems = gems;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
