package com.example.demo.entities;
// Generated Dec 3, 2019 5:50:24 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ParValue generated by hbm2java
 */
@Entity
@Table(name = "par_value", catalog = "testingdb")
public class ParValue implements java.io.Serializable {

	private Integer id;
	private Double amount;

	public ParValue() {
	}

	public ParValue(Double amount) {
		this.amount = amount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "AMOUNT", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

}
