package com.example.demo.entities;
// Generated Dec 3, 2019 5:50:24 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "testingdb")
public class Question implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Subject subject;
	private Double point;
	private String text;
	private int status;
	private Set<ExamQuestion> examQuestions = new HashSet<ExamQuestion>(0);
	private Set<QuestionSub> questionSubs = new HashSet<QuestionSub>(0);

	public Question() {
	}

	public Question(int status) {
		this.status = status;
	}

	public Question(Account account, Subject subject, Double point, String text, int status,
			Set<ExamQuestion> examQuestions, Set<QuestionSub> questionSubs) {
		this.account = account;
		this.subject = subject;
		this.point = point;
		this.text = text;
		this.status = status;
		this.examQuestions = examQuestions;
		this.questionSubs = questionSubs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_ID")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBJECT_ID")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@Column(name = "POINT", precision = 22, scale = 0)
	public Double getPoint() {
		return this.point;
	}

	public void setPoint(Double point) {
		this.point = point;
	}

	@Column(name = "TEXT", length = 250)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<ExamQuestion> getExamQuestions() {
		return this.examQuestions;
	}

	public void setExamQuestions(Set<ExamQuestion> examQuestions) {
		this.examQuestions = examQuestions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<QuestionSub> getQuestionSubs() {
		return this.questionSubs;
	}

	public void setQuestionSubs(Set<QuestionSub> questionSubs) {
		this.questionSubs = questionSubs;
	}

}
