package com.example.demo.entities;
// Generated Dec 3, 2019 5:50:24 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuestionSub generated by hbm2java
 */
@Entity
@Table(name = "question_sub", catalog = "testingdb")
public class QuestionSub implements java.io.Serializable {

	private Integer id;
	private Question question;
	private String text;
	private Integer coprrect;
	private Set<Answer> answers = new HashSet<Answer>(0);

	public QuestionSub() {
	}

	public QuestionSub(Question question, String text, Integer coprrect, Set<Answer> answers) {
		this.question = question;
		this.text = text;
		this.coprrect = coprrect;
		this.answers = answers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "TEXT", length = 250)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "COPRRECT")
	public Integer getCoprrect() {
		return this.coprrect;
	}

	public void setCoprrect(Integer coprrect) {
		this.coprrect = coprrect;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionSub")
	public Set<Answer> getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set<Answer> answers) {
		this.answers = answers;
	}

}
